### ISSUE TITLE
Outdated k8s apiVersion

### ISSUE THREAD

**Issue by xujinheng** [alauda/kubeflow-chart#2]
Hi,
I noticed many of the yaml files use outdated apiVersions, for example, this file https://github.com/alauda/kubeflow-chart/blob/main/charts/kubeflow/crds/notebooks-crd.yaml uses an api version `apiextensions.k8s.io/v1beta1` which has been replaced by `apiextensions.k8s.io/v1` in the k8s version since v1.22. Is there a way to bypass the issue?

**Comment by typhoonzero** [comment]
Kubeflow 1.4/1.5 supports only up to Kubernetes version 1.21, see https://github.com/kubeflow/kubeflow/issues/6098. We'll update this chart to support the latest Kubeflow version once the support of 1.22 comes.

**Comment by xujinheng** [comment]
Got it! Thanks
