### ISSUE TITLE
error： executing "kubeflow/templates/platform-agnostic-multi-user.yaml" at <.Values.mysql.host>: nil pointer evaluating interface {}.host

### ISSUE THREAD

**Issue by gggzzz1212** [alauda/kubeflow-chart#34]
helm lint kubeflow/
==> Linting kubeflow/
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: template: kubeflow/templates/platform-agnostic-multi-user.yaml:2208:20: executing "kubeflow/templates/platform-agnostic-multi-user.yaml" at <.Values.mysql.host>: nil pointer evaluating interface {}.host

在values.yaml中添加 mysql：host：“*” 后

(base) [root@k8s-master charts]# helm lint kubeflow
==> Linting kubeflow
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/: template: kubeflow/templates/platform-agnostic-multi-user.yaml:2559:9: executing "kubeflow/templates/platform-agnostic-multi-user.yaml" at <include "kubeflow.nodeAffinity" .>: error calling include: template: no template "kubeflow.nodeAffinity" associated with template "gotpl"

是我用的方式不对吗，求帮助

**Comment by gggzzz1212** [comment]
> `helm lint` 命令是用来检查 helm chart 代码格式的。如果是要安装，参考 `README.md` 中的安装方法。helm 使用的方法参考：https://helm.sh/zh/docs/intro/using_helm/

直接helm install 也是报这些错误

**Comment by typhoonzero** [comment]
@gggzzz1212 这个问题最新的代码已经修复了

**Comment by gggzzz1212** [comment]
> @gggzzz1212 这个问题最新的代码已经修复了

感谢~
